---
title: Princeton Dining Locations with Menus
dataObjects:
-   KGOLocation
args:
    dataModel: KGOLocationsDataModel
    dataRetriever: KGOURLDataRetriever
    dataParser: KGOXMLLocationsDataParser
    itemtype: princeton-dining-location
    eventsFeed:
        feedtype: ics
        itemtype: princeton-event-with-menu
        dataRetriever: KGODiningDataRetriever
        dataParser: KGODiningICSDataParser
config:
-   class: KGOFormElementControllerText
    validators:
    -   class: KGOURLValidator
    options:
        required: true
    fields:
        label: Locations Feed URL
        description: Locations Feed URL
    controller:
        upload: true
        config: baseURL
-   class: KGOFormElementControllerText
    validators:
    -   class: KGOURLValidator
    options:
        required: true
    fields:
        label: Menu JSON URL
        description: Menu JSON URL
    controller:
        upload: true
        config: menuURL
...
