---
title: Princeton Dining Locations
dataObjects:
-   KGOLocation
args:
    dataModel: KGOLocationsDataModel
    dataRetriever: KGOURLDataRetriever
    dataParser: PrincetonLocationsDataParser
    itemtype: princeton-dining-location
    eventsFeed:
        feedtype: ics
        itemtype: princeton-dining-event
config:
-   class: KGOFormElementControllerText
    validators:
    -   class: KGOURLValidator
    options:
        required: true
    fields:
        label: URL
        description: The URL to this feed
    controller:
        upload: true
        config: baseURL
...
