---
title: Princeton Catalog Federated Search Feed
args:
    dataModel: PrincetonCatalogFederatedSearchDataModel
    dataRetriever: PrincetonCatalogFederatedSearchDataRetriever
config:
-   class: KGOFormElementControllerText
    validators:
    -   class: KGOURLValidator
    options:
        required: true
    fields:
        label: URL
        description: The URL to this feed
    controller:
        upload: true
        config: baseURL
-   class: KGOFormElementControllerSelect
    fields:
        label: Terms Feed
        options:
            kgoResolveType: method
            kgoResolveValue: getFeedOptions
            kgoResolveArgs:
            -   ModoAcademicTermsDataModel
    controller:
        config: feeds.terms
...
