---
common:
    title: Princeton Athletics News
    dataObjects:
    -   KGONewsItem
    controllerConfigs:
        KGOUIListItemNews: info.objdefs.newsListItem
        KGOUIDetail: info.objdefs.detail
        KGOUICarouselItem: info.objdefs.carouselItem
    objdefs:
        newsListItem:
            fields:
                thumbnail:
                    kgoResolveType: value
                    kgoResolveValue: kgonews:thumbnail
                    kgoResolveProcessors:
                    -   class: KGOImageDataProcessor
                        options:
                            maxWidth: 100
                            maxHeight: 100
                            crop: true
                            backgroundRGB: '000000'
        detail:
            fields:
                description: null
                thumbnail:
                    kgoResolveType: value
                    kgoResolveValue: kgonews:thumbnail
                    kgoResolveProcessors:
                    -   class: KGOImageDataProcessor
                        options:
                            maxWidth: 100
                            maxHeight: 100
                            crop: true
                            backgroundRGB: '000000'
        carouselItem:
            fields:
                thumbnail:
                    kgoResolveType: value
                    kgoResolveValue: kgonews:thumbnail
                    kgoResolveProcessors:
                    -   class: KGOImageDataProcessor
                        options:
                            maxWidth: 100
                            maxHeight: 100
                            crop: true
                            backgroundRGB: '000000'
...