---
common:
    title: Princeton Event
    controllerConfigs:
        KGOUIDetail: info.objdefs.detail
    dataObjects:
    -   KGOCalendarEvent
    objdefs:
        detail:
            regions:
            -   name: content
                contents:
                -   class: KGOListController
                    requiresData: true
                    options:
                        inset: true
                        grouped: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.location
                    regions:
                    -   name: items
                        contents:
                        -   class: KGOListItemController
                            options:
                                accessory: map
                            fields:
                                title:
                                -   kgoResolveType: value
                                    kgoResolveValue: kgocalendar:location
                                    kgoResolveProcessors:
                                    -   class: KGOTrimToNullDataProcessor
                                subtitle: null
                                url:
                                -   kgoResolveType: value
                                    kgoResolveValue: kgocalendar:location
                                    kgoResolveProcessors:
                                    -   class: KGOTrimToNullDataProcessor
                                    -   class: KGOModuleSearchURLDataProcessor
                                        options:
                                            module: map
                                            command: ''
                                            args:
                                                _recenter: 'true'
                -   class: KGOListController
                    requiresData: true
                    options:
                        inset: true
                        grouped: true
                    fields:
                        heading: Tags
                    regions:
                    -   name: items
                        contents:
                        -   class: KGOListItemController
                            source:
                            -   kgoResolveType: value
                                kgoResolveValue: ics:CATEGORIES
                                kgoResolveProcessors:
                                -   class: KGOStringsToDataObjectsDataProcessor
                -   class: KGOHTMLController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.description
                        html:
                        -   kgoResolveType: value
                            kgoResolveValue: kgo:description
                            kgoResolveProcessors:
                            -   class: KGOTrimToNullDataProcessor
                -   class: KGOListController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.website
                    options:
                        grouped: true
                        inset: true
                    regions:
                    -   name: items
                        contents:
                        -   class: KGOListItemController
                            source:
                            -   kgoResolveType: value
                                kgoResolveValue: kgocalendar:url
                                kgoResolveProcessors:
                                -   class: KGOTrimToNullDataProcessor
                                -   class: KGOURLsToLinksDataProcessor
...
