---
common:
    title: Princeton Dining Event with Menu
    controllerConfigs:
        KGOUIDetail: info.objdefs.detail
    dataObjects:
    -   KGOCalendarEvent
    objdefs:
        detail:
            regions:
            -   name: content
                contents:
                -   class: KGOHTMLController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.location
                        html:
                        -   kgoResolveType: value
                            kgoResolveValue: kgocalendar:location
                            kgoResolveProcessors:
                            -   class: KGOTrimToNullDataProcessor
                -   class: KGOHTMLController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.description
                        html:
                        -   kgoResolveType: value
                            kgoResolveValue: kgo:description
                            kgoResolveProcessors:
                            -   class: KGOTrimToNullDataProcessor
                            -   class: KGOHTMLEncodeDataProcessor
                -   class: KGOListController
                    requiresData: false
                    fields:
                        heading: Menu
                    options:
                        grouped: true
                        inset: true
                    regions:
                    -   name: items
                        contents:
                        -   class: KGOListItemController
                            uiClass: KGOUIListItemMenuOption
                            source:
                            -   kgoResolveType: method
                                kgoResolveValue: getMealItems
                            fieldFormatters:
                                title: []
                            fields:
                                title:
                                -   kgoResolveType: inherit
                                    kgoResolveProcessors:
                                    -   class: PrincetonAppendNutritionIconsDataProcessor
                                url:
                                -   kgoResolveType: value
                                    kgoResolveValue: menu:link
                                    kgoResolveProcessors:
                                    -   class: KGOURLDataProcessor
                -   class: KGOHTMLController
                    options:
                        focal: true
                        inset: true
                    fields:
                        heading: Legend
                        html:
                        -   kgoResolveType: inherit
                            kgoResolveProcessors:
                            -   class: PrincetonNutritionLegendDataProcessor
                -   class: KGOListController
                    requiresData: true
                    fields:
                        heading:
                        -   kgoResolveType: localize
                            kgoResolveValue: core.ui.calendar.headings.website
                    options:
                        grouped: true
                        inset: true
                    regions:
                    -   name: items
                        contents:
                        -   class: KGOListItemController
                            source:
                            -   kgoResolveType: value
                                kgoResolveValue: kgocalendar:url
                                kgoResolveProcessors:
                                -   class: KGOTrimToNullDataProcessor
                                -   class: KGOURLsToLinksDataProcessor
...
